FROM node:14-alpine

USER node

WORKDIR /usr/src/app

COPY --chown=node ./front/package*.json ./

RUN yarn install

COPY --chown=node ./front .

EXPOSE 3000
CMD ["sh", "-c", "'yarn build ; yarn start'" ]