FROM node:14-alpine

USER node

WORKDIR /usr/src/app

COPY --chown=node ./api/package*.json ./

RUN npm install

COPY --chown=node ./api .

EXPOSE 8000
CMD [ "sh", "-c", "npm run build ;npm run dev:watch" ]